### ISSUE TITLE
Thank you for your work. Coulde you provide more detailed guidance and instructions?

### ISSUE THREAD

**Issue by Today20180409** [adler-1994/gmcl#1]
Thank you for your work. Coulde you provide more detailed guidance and instructions?

**Comment by adler-1994** [comment]
Hello, 
Thnaks for your comment....
if you have previous experience with amcl package then you could deal with this package in the same way.. but you have to pay attention to the ROS parameters imposed by gmcl to work error free.
you can see more info in this ROS wiki page http://wiki.ros.org/gmcl

**Comment by li9i** [comment]
Hello @adler-1994, and thank you very much for all of your great work. I would like to ask you this question: It seems to me that if I wanted to globally localise a robot with gmcl, I should (a) call the `global_localization` service and then (b) look at the hypothesis cluster with the largest weight. Is this true, or is something else needed additionally? I could not tell from reading your paper. Thank you very much in advance.
