### ISSUE TITLE
Some questions about the paper 

### ISSUE THREAD

**Issue by Jason-Lee0** [adler-1994/gmcl#2]
Hi, I am very interested in your work.
Here are some questions I want to ask, thanks for your help !! 

(1) In your paper, I saw the parameters called "energy_map_resolution_x" and "energy_map_resolution_y". 

What are their meanings? 
In my thought, I think it's the range from the center of the sensor. In this range, the filter will calculate the SER.
Is my thought right? 

(2) In your experiment(1), you decide the specific position for the robot. Then use different methods to calculate the RMSE.
How did you set the specific position of the robot? And how did you calculate the RMSE at every point? 

Sorry to bother you.  Thanks for your reading and hard work!!
Have a nice day ~~

**Comment by adler-1994** [comment]
Hello, 

I am so glad you are interested in using my package.
 
For part (1) of your question: 
energy_map_resolution_x and -resolution parameters are not correlated with sensors. These parameters only decide how dense the SER - orange area  in the youtube video - could be in the original map. The smaller the parameter is the denser SER becomes...

For part (2) of your question: 
To set the robot in gazebo where ever you want , use the following command..but be careful to the "model_name"
for example:
$ rostopic pub -1 /gazebo/set_model_state gazebo_msgs/ModelState "model_name: 'turtlebot3_burger'                 
pose:
  position:
    x: -6.5
    y: 5.5
    z: 0.65
  orientation:
    x: 0.0
    y: 0.0
    z: -0.707
    w: 0.707
"
 
To calculate the RMSE .. I made a simple subscriber node that takes odom position from gazebo and the position estimated by gmcl then calculates RMSE and writes it to an external .txt file.  

I hope this reply has addressed thoroughly your questions and please don’t say “Sorry to bother you” again..You are welcome at any time.

Have a nice day
