### ISSUE TITLE
ROS2 version

### ISSUE THREAD

**Issue by HappySamuel** [adler-1994/gmcl#3]
Hi

Do you have any ROS2 gmcl version? I would like to try it out.

Best,
Samuel

**Comment by adler-1994** [comment]
Thanks for your question Samuel.

Unfortunately, gmcl is currently only available on ROS1. However, if you have both ROS1 and ROS2 in your computer, you can use ros1_bridge package in order to make ros1 and ros2 packages able to communicate with each other…

Wish you a good day,
