### ISSUE TITLE
Node dies after receiving Map

### ISSUE THREAD

**Issue by MaxikingZ** [adler-1994/gmcl#4]
Hello, thank you for providing an alternative to the amcl. 

I really want to try it compared to the amcl, since I have a lot of trouble in more complex environments.
Sadly, I cannot get the GMCL to start. Since I use my own Map Server I used the use_map_topic param. The node also seems to get the Map.
`[ INFO] [1655197709.379978395]: Subscribed to map topic.
[ INFO] [1655197713.441459081]: Received a 608 X 384 map @ 0.050 m/pix`
But after that it crashes. For testing I removed line 963 in the gmcl_node.cpp
`  freeMapDependentMemory();`. This allowed me to at least start the node. 
But I did not had time to test the functionality yet.

Thank you for taking your time reading that.

**Comment by adler-1994** [comment]
Hello MaxikingZ, I hope you are doing well.  Try to set the first_map_only parameter to true. This might avoid the node crash.

I hope I could help you and wish you a nice day.
