### ISSUE TITLE
The node crashes by calling the global location service and using self adaptive [Ros Melodic]

### ISSUE THREAD

**Issue by Daxturtle** [adler-1994/gmcl#5]
hi, I am interested in comparing your GMCL algorithm with AMCL.  When I start the global location service with optimal filter and inteligent filter it runs fine. If I also activate self adaptive it crashes. Is it incompatible with Ros Melodic? Thank you for your work.

**Comment by adler-1994** [comment]
Hello and sorry for the late replay.

GMCL package has been only tested on ROS noetic. I recommned you to use noetic Distro, since it is the latest LTS ROS distribution.

I hope I could help you and wish you a nice day.
