### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by Vuwij** [adler-1994/gmcl#6]
The outcome looks great but there are no tests which is making it difficult for new people to use this package

**Comment by adler-1994** [comment]
Hello and thanks for your comment.

GMCL package behaves in a similar manner to AMCL package as it subscribes to the same topics and uses the same services. Just pay attention to the extra ROS parameters that gmcl uses mentioned here http://wiki.ros.org/gmcl

I hope I could help you and wish you a nice day.
